### ISSUE TITLE
Expose xdg-open-with-portal as nixosModules.xdg-open-workaround

### ISSUE THREAD

**Issue by PAI5REECHO** [LunNova/nixos-configs#5]
Can you please supply your script to workaround https://github.com/NixOS/nixpkgs/issues/160923 as `nixosModules.xdg-open-workaround` so I can use it easily?

**Comment by LunNova** [comment]
The package should be available already as a flake output at `packages.${system}.xdg-open-with-portal` unless I messed up. Is it not there?

**Comment by LunNova** [comment]
Oh I see you want a module to workaround it for everything... I haven't made it yet, I've been overriding xdg-utils in the inputs for specific apps when I run into problems.

Maybe later? (:

**Comment by PAI5REECHO** [comment]
Sorry I'm trying to wrap my head around how to use this. Say I want to use `xdg-open-with-portal` for the Electron AppImage package `session-desktop-appimage`. What would that look like?

**Comment by LunNova** [comment]
This should be done now as a module at `nixosModules.xdg-open-workaround`.

Might be a long and slow rebuild as there are a lot of packages which depend on xdg-utils directly instead of picking it up from the path.

**Comment by PAI5REECHO** [comment]
Alright, I'll give it a spin soon

**Comment by LunNova** [comment]
Did you get a chance to try this yet?

**Comment by PAI5REECHO** [comment]
I did, I A/B tested some stuff I can't remember if it fixed any app that was previously broken with link opening
